export const types = {
  FETCH_EVENTS: "FETCH_EVENTS",
  FETCH_EVENTS_REQUESTED: "FETCH_EVENTS_REQUESTED",
  FETCH_EVENTS_RECEIVED: "FETCH_EVENTS_RECEIVED",
  FETCH_EVENTS_FAILED: "FETCH_EVENTS_FAILED"
};
