export const types = {
  FETCH_MEMBERS: "FETCH_MEMBERS",
  FETCH_MEMBERS_REQUESTED: "FETCH_MEMBERS_REQUESTED",
  FETCH_MEMBERS_RECEIVED: "FETCH_MEMBERS_RECEIVED",
  FETCH_MEMBERS_FAILED: "FETCH_MEMBERS_FAILED"
};
